server:
  port: 8091

spring:
  application:
    name: xis-cv-personal-information-microservice
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: 192.168.31.155
      port: 27017
      database: XIS-CV
      username: username
      password: password
      authentication-database: admin
  jackson:
    date-format: yyyy-MM-dd
  security:
    oauth2:
      resourceserver:
        issuer-uri: http://192.168.31.155:28080/realms/master
        jwk-set-uri: http://192.168.31.155:28080/realms/master/protocol/openid-connect/certs

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.31.155:8761/eureka/

management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'