server:
  port: 8091

spring:
  application:
    name: xis-cv-personal-information-microservice
  data:
    mongodb:
      # host: localhost
      # port: 27017
      # database: XIS-CV
      # username: xis-cv
      # password: xis-cv
      uri: mongodb://xis-cv:xis-cv@localhost:27017/XIS-CV?authSource=admin&retryWrites=true&w=majority

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://200.234.224.203:8761/eureka/