server:
  port: 8091

spring:
  application:
    name: xis-cv-personal-information-microservice
  data:
    mongodb:
      host: 192.168.31.155
      port: 27017
      database: XIS-CV
      username: username
      password: password
      authentication-database: admin
  jackson:
    date-format: yyyy-MM-dd
  security:
    oauth2:
      resourceserver:
          issuer-uri: http://192.168.31.155:28080/auth/realms/master
          jwk-set-uri: http://192.168.31.155:28080/auth/realms/master/protocol/openid-connect/certs

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.31.155:8761/eureka/