server:
  port: 8091

spring:
  application:
    name: xis-cv-personal-information-microservice
  data:
    mongodb:
      host: localhost
      port: 27017
      database: XIS-CV
      username: xis-cv
      password: xis-cv

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://200.234.224.203:8761/eureka/