server:
  port: 8080

spring:
  application:
    name: xis-cv-gateway
  cloud:
    gateway:
      routes:
        - id: personal-information-service
          uri: lb://xis-cv-personal-information-api
          predicates:
            - Path=/xis/v1/personal-information/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/