server:
  port: 8091

spring:
  application:
    name: xis-cv-personal-information-microservice
  data:
    mongodb:
      host: 192.168.31.155
      port: 27017
      database: XIS-CV
      username: username
      password: password
      authentication-database: admin
  jackson:
    date-format: yyyy-MM-dd

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.31.155:8761/eureka/